# mass of sub (kg)
m: 23.85
# center of mass
x_m: 0.0
y_m: 0.0
z_m: 0.0
# center of buoyancy
x_b: 0.000000000001
y_b: 0.000000000001
z_b: 0.000000000001
# gravity (m/s^2)
g: 9.81
# density of water (kg/m^3)
rho: 997.0
# buoyancy force
Fb: 250.479
# Fb: 140.479
# moments of inertia
Ixx: 1.0
Iyy: 1.0
Izz: 1.0
# locations of motors
# max thrust multipliers (if motor is flipped, make f negative)
T_L:
    x: 0.0
    y: -1.0
    z: 0.0
    f: 18.237
T_R:
    x: 0.0
    y: 1.0
    z: 0.0
    f: 18.237
T_F:
    x: 1.0
    y: 0.0
    z: 0.0
    f: 18.237
T_B:
    x: -1.0
    y: 0.0
    z: 0.0
    f: 18.237
T_FR:
    x: 1.0
    y: 1.0
    z: 0.0
    f: 18.237
T_FL:
    x: 1.0
    y: -1.0
    z: 0.0
    f: 18.237
T_BR:
    x: -1.0
    y: 1.0
    z: 0.0
    f: 18.237
T_BL:
    x: -1.0
    y: -1.0
    z: 0.0
    f: 18.237
# Drag coefficients
Cd_x: 0.2
Cd_y: 0.2
Cd_z: 0.2

# top, bottom, left, right
# intersection of y along x axis
Cd_xT: 0.2
Cd_xB: 0.2
# intersection of z along x axis
Cd_xR: 0.2
Cd_xL: 0.2

# top, bottom, front, back
# intersectoin of x along y axis
Cd_yT: 0.2
Cd_yB: 0.2
# intersectoin of z along y axis
Cd_yF: 0.2
Cd_yBa: 0.2

# left, right, front, back
# intersectoin of x along z axis
Cd_zL: 0.2
Cd_zR: 0.2
# intersectoin of y along z axis
Cd_zF: 0.2
Cd_zB: 0.2

# Surface areas
A_x: 1.0
A_y: 1.0
A_z: 1.0

# top, bottom, left, right
A_xT: 1.0
A_xB: 1.0
A_xR: 1.0
A_xL: 1.0

# top, bottom, front, back
A_yT: 1.0
A_yB: 1.0
A_yF: 1.0
A_yBa: 1.0

# left, right, front, back
A_zL: 1.0
A_zR: 1.0
A_zF: 1.0
A_zB: 1.0

# Moment arm lengths
# how to read:
# dz_xT = distance along z axis to center of top slice viewed in the x direction
dz_xT: -1.0
dz_xB: 1.0
dy_xR: 1.0
dy_xL: -1.0

dz_yT: -1.0
dz_yB: 1.0
dx_yF: 1.0
dx_yBa: -1.0

dy_zL: -1.0
dy_zR: 1.0
dx_zF: 1.0
dx_zB: -1.0
